config/routes.rb
MladiinfoSocial::Application.routes.draw do
  get "static_pages/index"
  root "static_pages#index"
  resources :users
  resources :topics
  resources :posts
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  validates :username, presence: true, length: { maximum: 25 }

  before_save { self.email = email.downcase }
  has_secure_password
  validates :password, length: { minimum: 6}

  before_create :create_remember_token

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def new
    @topic = Topic.new
  end
end

app/controllers/users_controller.rb
# coding: utf-8
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update, :index, :destroy]
  before_action :correct_user,   only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
      if @user.save
      sign_in @user
      flash[:success] = "Účet úspěšně vytvořen"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profil upraven"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end



  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

    def signed_in_user
      redirect_to signin_url unless signed_in?
      flash[:notice] = "Prosím přihlaš se" unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user)
    user == current_user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size = 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mladiinfo Social</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- navbar -->
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Mladiinfo Social</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <% if signed_in? %>
            <li><%= link_to "Uživatelé", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= current_user.username %>
                <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Můj profil", current_user %></li>
                <li><%= link_to "Nastavení", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Odhlásit se", signout_path, method: "delete" %></li>
        <% else %>
            <li><a href="/signup">Registrace</a></li>
            <li><%= link_to "Přihlásit se", signin_path %></li>
        <% end %>
        </ul>
        </li>
        <% if signed_in? %>
           <li><%= link_to "Diskuze", topics_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<!-- flash message -->
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<!-- content of each pages will render here -->
<div class="container">
  <%= yield %>
</div>

<!-- footer -->
<div class="footer">
  <%= image_tag 'mladiinfo.png', :class => 'logo_img' %>
  <a href="https://www.facebook.com/mladiinfoCR"><%= image_tag "fb.png", :class => "fb-icon" %></a>

  <p>Dobrovolnictví | Stáže | Neformální vzdělávání | Studium | Cestování </p>
</div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/index.html.erb
<h1 class="title">Mladiinfo Social</h1>
<div class="row">
  <div class="col-md-12">
    <h3 class="orange">Diskutuj o svých zážitcích, hodnoť je, čti si názory ostatních a spoj se s lidmi které baví to co tebe - užívat si svá studentská léta naplno a smysluplně!</h3>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <h3> Co je Mladiinfo? </h3>
    <p>Jsme občanské sdružení, které se snaží podporovat mladé lidi v aktivním a smysluplném trávení volného času a inspirovat je zejména k dobrovolnictví, neformálnímu vzdělávání, stážím, studiu a cestování. Provozujeme webové stránky <a href="www.mladiinfo.cz"> www.mladiinfo.cz </a> kde najdete denně čerstvé novinky, články a příležitosti.  </p>
    <h3> Proč sociální síť?</h3>
    <p>Mladiinfo social je náš projekt jakým se snažíme spojit dohromady lidi, kteří mají podobný způsob života. Chceme vytvořit komunitu, kde bude možné sdílet své zkušenosti z dobrovolnictví, trainingů, výměn mládeže, ... a kde bude možné se inspirovat, přiučit a dozvědět nové věci od těch, co to zažili.</p>
  </div>
  <div class="col-md-6">

    <%= form_tag "/sessions" do %>
      <h3 class="center"> Přihlaš se </h3>
      Email <input type="text" name="session[email]">
      Password <input type="password" name="session[password]">
      <br>
      <button type="submit" class="btn btn-orange">Potvrdit</button>
    <% end %>

    <span> Ještě nemáš účet? <%= link_to "Přidej se hned teď!", signup_path, class: "btn btn-large btn-primary" %></span>
  </div>
</div>
<br />
<div class="row">
  <div class="col-md-12">
    <p><u>Ochutnávka témat a rad, jaké se zde můžete dozvědět:</u> jaké to je jet na rok na EVSku, jaké to je být na Erasmu, co obnáší mezinárodní výměna mládeže, kde se naučit jazyky zadarmo, na co si dát pozor při stopování, jaké existují stipendia, proč by člověk měl pracovat zadarmo, co to je Mládež v akci, co to jsou víkendovky, jak se učí neformálně, kam se dá jet na tábor pro vysokoškláky a mnohé další.</p>
  </div>
</div>
<hr>
<div class="row last">
  <div class="col-md-6">
    <h3> Novinky v Mladiinfo světě </h3>
    <div id="carousel-example-generic" class="carousel slide">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="item active">
          <img src="https://fbcdn-sphotos-a-a.akamaihd.net/hphotos-ak-prn2/1238074_500548086704114_983319375_n.jpg" alt="...">
          <div class="carousel-caption">

          </div>
        </div>
        <div class="item">
          <%= image_tag "social.png" %>
          <div class="carousel-caption">

          </div>
        </div>
        <div class="item">
          <%= image_tag "pruvodce.png" %>
          <div class="carousel-caption">

          </div>
        </div>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
        <span class="icon-prev"></span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
        <span class="icon-next"></span>
      </a>
    </div>
  </div>
  <div class="col-md-6">
    <h3> Nejnovější příspěvky v diskuzi </h3>
  </div>
</div>
<%= image_tag "bubble2.png", :class => "bubble" %>

app/views/topics/index.html.erb
<div class="discussion">
  <div class="row">
    <div class="col-md-10"><h2>Diskuzní fórum</h2></div>
    <div class="col-md-2">
     <%= link_to "Založit nové téma", new_topic_path, class: "btn btn-primary new_topic"  %>
    </div>
  </div>
  <hr>
  <table class="table-condensed">
    <tr class="header">
      <td>
        <span>Téma</span>
      </td>
      <td>
        <span>Kategorie</span>
      </td>
      <td>
        <span>Příspěvků</span>
      </td>
      <td>
        <span>Autor</span>
      </td>
      <td>
        <span>Počet hlasů</span>
      </td>
    </tr>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.title %></td>
        <td>
          <span class="category">Dobrovolnictví</span>
        </td>
        <td>
          <span>10</span>
        </td>
        <td>
          <%= gravatar_for topic.user, 20 %>
          <span>Jocellyn</span>
        </td>
        <td>
          <span>32</span>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user%>
  <%= link_to user.username, user %>
  <% if current_user.admin? && !current_user?(user) %>
      | <%= link_to "delete", user, method: :delete,
                    data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<h1>Upravit profil</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :username %>
      <%= f.text_field :username %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Potvrdit", class: "btn btn-large btn-primary", id: "edit" %>
      <% end %>
    <br />
    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">Změnit gravatar</a>
  </div>
</div>

app/views/users/index.html.erb
<h1>Všichni uživatelé</h1>

<%= will_paginate%>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate%>

app/views/users/new.html.erb
<h1>Zaregistruj nový účet</h1>
<h3 class="orange center"> Přidej se k debatě, isnpiruj se zážitky ostatních! </h3>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :username %>
      <%= f.text_field :username %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Vytvoř účet", class: "btn btn-large btn-orange", id: "submit" %>
    <% end %>
  </div>
</div>
<%= image_tag "bubble.png", :class => "bubble_left" %>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section>
      <h1>
        <%= gravatar_for @user, 80 %>
        <%= @user.username %>
      </h1>
    </section>
  </aside>
</div>